
export const data = [{
    image : "/robertdowneyjr.jpg",
    description: "Actor / Producer",
    fame: true,
    name: "Robert",
    surname: "Downey Jr.",
    birthdate: "04/03/1965",
    deathdate : "null",
    age: 55,
    ethnicity: "White",
    nationality: "American",
    gender: "Male",
},{
    image : "/chrisevans.jpg",
    description: "Actor / Producer",
    fame: true,
    name: "Chris",
    surname: "Evans",
    birthdate: "13/06/1981",
    deathdate : "null",
    age: 38,
    ethnicity: "White",
    nationality: "American",
    gender: "Male",
},{
    image : "/markalanruffalo.jpg",
    description: "Actor / Producer",
    fame: true,
    name: "Mark Alan",
    surname: "Ruffalo",
    birthdate: "22/11/1967",
    deathdate : "null",
    age: 52,
    ethnicity: "White",
    nationality: "American",
    gender: "Male",
},{
    image : "/chrishems.jpg",
    description: "Actor",
    fame: true,
    name: "Chris",
    surname: "Hemsworth",
    birthdate: "11/08/1983",
    deathdate : "null",
    age: 36,
    ethnicity: "White",
    nationality: "Australian",
    gender: "Male",
},{
    image : "/scarletjohansson.jpg",
    description: "Actress/Producer/Writer",
    fame: true,
    name: "Scarlett",
    surname: "Johansson",
    birthdate: "22/11/1984",
    deathdate : "null",
    age: 35,
    ethnicity: "White",
    nationality: "American",
    gender: "Female",
},{
    image : "/jeremyrenner.jpg",
    description: "Actor/Producer",
    fame: true,
    name: "Jeremy",
    surname: "Renner",
    birthdate: "07/01/1971",
    deathdate : "null",
    age: 49,
    ethnicity: "White",
    nationality: "American",
    gender: "Male",
},{
    image : "/tomhiddleston.jpg",
    description: "Actor",
    fame: true,
    name: "Tom",
    surname: "Hiddleston",
    birthdate: "09/02/1981",
    deathdate : "null",
    age: 39,
    ethnicity: "White",
    nationality: "British",
    gender: "Male",
},{
    image : "/stellan-skarsgard.jpg",
    description: "Actor",
    fame: true,
    name: "Stellan",
    surname: "Skarsgård",
    birthdate: "13/06/1951",
    deathdate : "null",
    age: 68,
    ethnicity: "White",
    nationality: "Swedish",
    gender: "Male",
},{
    image : "/samuelljackson.jpg",
    description: "Actor/Producer",
    fame: true,
    name: "Samuel L.",
    surname: "Jackson",
    birthdate: "21/12/1948",
    deathdate : "null",
    age: 71,
    ethnicity: "Black",
    nationality: "American",
    gender: "Male",
},{
    image : "/clarkgregg.jpg",
    description: "Actor/Producer",
    fame: true,
    name: "Clark",
    surname: "Gregg",
    birthdate: "02/04/1962",
    deathdate : "null",
    age: 58,
    ethnicity: "White",
    nationality: "American",
    gender: "Male",
},{
    image : "/cobiesmulders.jpg",
    description: "Actress/Producer",
    fame: true,
    name: "Cobie",
    surname: "Smulders",
    birthdate: "03/04/1982",
    deathdate : "null",
    age: 38,
    ethnicity: "White",
    nationality: "Canadian",
    gender: "Female",
},{
    image : "/gwynethpaltrow.jpg",
    description: "Actress/Producer",
    fame: true,
    name: "Gwyneth",
    surname: "Paltrow",
    birthdate: "27/09/1972",
    deathdate : "null",
    age: 47,
    ethnicity: "White",
    nationality: "American",
    gender: "Female",
},{
    image : "/jennyagutter.jpg",
    description: "Actress",
    fame: true,
    name: "Jenny",
    surname: "Agutter",
    birthdate: "20/12/1952",
    deathdate : "null",
    age: 67,
    ethnicity: "White",
    nationality: "British",
    gender: "Female",
},{
    image : "/Walter_Perez.jpg",
    description: "Actor",
    fame: true,
    name: "Walter",
    surname: "Perez",
    birthdate: "12/07/1982",
    deathdate : "null",
    age: 37,
    ethnicity: "White",
    nationality: "American",
    gender: "Male",
},{
    image : "/Paul_Bettany.jpg",
    description: "Actor",
    fame: true,
    name: "Paul",
    surname: "Bettany",
    birthdate: "27/03/1971",
    deathdate : "null",
    age: 48,
    ethnicity: "White",
    nationality: "British",
    gender: "Male",
},{
    image : "/James_Cameron.jpg",
    description: "Actor",
    fame: true,
    name: "James",
    surname: "Cameron",
    birthdate: "26/08/1954",
    deathdate : "null",
    age: 65,
    ethnicity: "White",
    nationality: "Canadian",
    gender: "Male",
},{
    image : "/samworthington.jpg",
    description: "Actor/Producer",
    fame: true,
    name: "Sam",
    surname: "Worthington",
    birthdate: "02/08/1976",
    deathdate : "null",
    age: 43,
    ethnicity: "White",
    nationality: "Australian",
    gender: "Male",
},{
    image : "/Zoe_Saldana.jpg",
    description: "Actress/Producer",
    fame: true,
    name: "Zoe",
    surname: "Saldana",
    birthdate: "19/06/1978",
    deathdate : "null",
    age: 41,
    ethnicity: "Puerto Rican",
    nationality: "American",
    gender: "Female",
},{
    image : "/siowea.jpg",
    description: "Actress/Producer",
    fame: true,
    name: "Sigourney",
    surname: "Weaver",
    birthdate: "08/10/1949",
    deathdate : "null",
    age: 70,
    ethnicity: "White",
    nationality: "American",
    gender: "Female",
},{
    image : "/Stephen-Lang-GettyImages-546301674-rcm300x428u.jpg",
    description: "Actor/Producer",
    fame: true,
    name: "Stephen",
    surname: "Lang",
    birthdate: "11/07/1952",
    deathdate : "null",
    age: 67,
    ethnicity: "White",
    nationality: "American",
    gender: "Male",
},{
    image : "/Michelle+Rodriguez.jpg",
    description: "Actress",
    fame: true,
    name: "Michelle",
    surname: "Rodriguez",
    birthdate: "12/07/1978",
    deathdate : "null",
    age: 41,
    ethnicity: "Puerto Rican",
    nationality: "American",
    gender: "Female",
},{
    image : "/Antoine_Fuqua_(29682821190).jpg",
    description: "Producer",
    fame: true,
    name: "Antoine",
    surname: "Fuqua",
    birthdate: "19/01/1966",
    deathdate : "null",
    age: 54,
    ethnicity: "Black",
    nationality: "American",
    gender: "Male",
},{
    image : "/Gerard_Butler_(29681162176).jpg",
    description: "Actor/Producer",
    fame: true,
    name: "Gerard",
    surname: "Butler",
    birthdate: "13/11/1969",
    deathdate : "null",
    age: 50,
    ethnicity: "White",
    nationality: "British",
    gender: "Male",
},{
    image : "/morganfreeman.jpg",
    description: "Actor/Producer",
    fame: true,
    name: "Morgan",
    surname: "Freeman",
    birthdate: "01/06/1937",
    deathdate : "null",
    age: 82,
    ethnicity: "Black",
    nationality: "American",
    gender: "Male",
},{
    image : "/melissaleo.jpg",
    description: "Actress",
    fame: true,
    name: "Melissa",
    surname: "Leo",
    birthdate: "14/09/1960",
    deathdate : "null",
    age: 59,
    ethnicity: "White",
    nationality: "American",
    gender: "Female",
},{
    image : "/Alvaro-Morte.jpg",
    description: "Actor",
    fame: true,
    name: "Álvaro",
    surname: "Morte",
    birthdate: "23/02/1975",
    deathdate : "null",
    age: 45,
    ethnicity: "Hispanic",
    nationality: "Spanish",
    gender: "Male",
},{
    image : "/ursulacorbero.jpg",
    description: "Actress",
    fame: true,
    name: "Úrsula",
    surname: "Corberó",
    birthdate: "11/08/1989",
    deathdate : "null",
    age: 30,
    ethnicity: "Hispanic",
    nationality: "Spanish",
    gender: "Female",
},{
    image : "/dedektiflacase.jpg",
    description: "Actress",
    fame: true,
    name: "Itziar",
    surname: "Ituño",
    birthdate: "18/06/1974",
    deathdate : "null",
    age: 45,
    ethnicity: "Hispanic",
    nationality: "Spanish",
    gender: "Female",
},{
    image : "/jaimelorente.jpg",
    description: "Actor",
    fame: true,
    name: "Jaime",
    surname: "Lorente",
    birthdate: "12/12/1991",
    deathdate : "null",
    age: 28,
    ethnicity: "Hispanic",
    nationality: "Spanish",
    gender: "Male",
},{
    image : "/darkoperic.jpg",
    description: "Actor",
    fame: true,
    name: "Darko",
    surname: "Peric",
    birthdate: "25/03/1977",
    deathdate : "null",
    age: 43,
    ethnicity: "Serbs",
    nationality: "Serbia",
    gender: "Male",
},{
    image : "/Pedro-Alonso.jpg",
    description: "Actor",
    fame: true,
    name: "Pedro ",
    surname: "Alonso",
    birthdate: "21/06/1971",
    deathdate : "null",
    age: 48,
    ethnicity: "Hispanic",
    nationality: "Spanish",
    gender: "Male",
},{
    image : "/Miguel-Herrán.jpg",
    description: "Actor",
    fame: true,
    name: "Miguel",
    surname: "Herrán",
    birthdate: "25/04/1996",
    deathdate : "null",
    age: 23,
    ethnicity: "Hispanic",
    nationality: "Spanish",
    gender: "Male",
},{
    image : "/elizataylor.jpg",
    description: "Actress",
    fame: true,
    name: "Eliza",
    surname: "Taylor",
    birthdate: "24/10/1989",
    deathdate : "null",
    age: 30,
    ethnicity: "White",
    nationality: "Australian",
    gender: "Female",
},{
    image : "/Paige-Turco-height.jpg",
    description: "Actress",
    fame: true,
    name: "Paige",
    surname: "Turco",
    birthdate: "17/05/1965",
    deathdate : "null",
    age: 54,
    ethnicity: "White",
    nationality: "American",
    gender: "Female",
},{
    image : "/bobmorley.jpg",
    description: "Actor",
    fame: true,
    name: "Bob",
    surname: "Morley",
    birthdate: "20/12/1984",
    deathdate : "null",
    age: 35,
    ethnicity: "White",
    nationality: "Australian",
    gender: "Male",
},{
    image : "/mariethe100.jpg",
    description: "Actress",
    fame: true,
    name: "Marie",
    surname: "Avgeropoulos",
    birthdate: "17/06/1986",
    deathdate : "null",
    age: 33,
    ethnicity: "White",
    nationality: "Canadian",
    gender: "Female",
},{
    image : "/Henry_ian_cusick.jpg",
    description: "Actor/Producer",
    fame: true,
    name: "Henry Ian",
    surname: "Cusick",
    birthdate: "17/04/1967",
    deathdate : "null",
    age: 53,
    ethnicity: "White/Hispanic",
    nationality: "British/ Peruvian",
    gender: "Male",
},{
    image : "/lindseymorgan.jpg",
    description: "Actress",
    fame: true,
    name: "Lindsey",
    surname: "Morgan",
    birthdate: "27/02/1990",
    deathdate : "null",
    age: 30,
    ethnicity: "Irish/Mexican",
    nationality: "American",
    gender: "Female",
},{
    image : "/chelseyreist.jpg",
    description: "Actress",
    fame: true,
    name: "Chelsey",
    surname: "Reist",
    birthdate: "04/01/1987",
    deathdate : "null",
    age: 33,
    ethnicity: "White",
    nationality: "Canadian",
    gender: "Female",
},{
    image : "/adinaporter.jpg",
    description: "Actress",
    fame: true,
    name: "Adina",
    surname: "Porter",
    birthdate: "13/03/1971",
    deathdate : "null",
    age: 49,
    ethnicity: "Black",
    nationality: "American",
    gender: "Female",
},{
    image : "/Tom_Ellis.jpg",
    description: "Actor",
    fame: true,
    name: "Tom",
    surname: "Ellis",
    birthdate: "17/11/1978",
    deathdate : "null",
    age: 41,
    ethnicity: "White",
    nationality: "British",
    gender: "Male",
},{
    image : "/davidbwoodside.jpg",
    description: "Actor",
    fame: true,
    name: "David B.",
    surname: "Woodside",
    birthdate: "25/07/1969",
    deathdate : "null",
    age: 50,
    ethnicity: "Black",
    nationality: "American",
    gender: "Male",
},{
    image : "/Rachael_Harris.jpg",
    description: "Actress",
    fame: true,
    name: "Rachael",
    surname: "Harris",
    birthdate: "12/01/1968",
    deathdate : "null",
    age: 52,
    ethnicity: "White",
    nationality: "American",
    gender: "Female",
},{
    image : "/lesleyannbrandy.jpg",
    description: "Actress",
    fame: true,
    name: "Lesley-Ann",
    surname: "Brandt",
    birthdate: "02/12/1981",
    deathdate : "null",
    age: 38,
    ethnicity: "African",
    nationality: "South Africa",
    gender: "Female",
},{
    image : "/alejandro_kevin.jpg",
    description: "Actor",
    fame: true,
    name: "Kevin",
    surname: "Alejandro",
    birthdate: "07/04/1976",
    deathdate : "null",
    age: 44,
    ethnicity: "White",
    nationality: "American",
    gender: "Male",
},{
    image : "/laurengerman.jpg",
    description: "Actress",
    fame: true,
    name: "Lauren",
    surname: "German",
    birthdate: "29/11/1978",
    deathdate : "null",
    age: 41,
    ethnicity: "White",
    nationality: "American",
    gender: "Female",
},{
    image : "/cillianmurphy.jpg",
    description: "Actor",
    fame: true,
    name: "Cillian",
    surname: "Murphy",
    birthdate: "25/05/1976",
    deathdate : "null",
    age: 43,
    ethnicity: "Scottish",
    nationality: "Irish",
    gender: "Male",
},{
    image : "/helenmccrory.jpg",
    description: "Actress",
    fame: true,
    name: "Helen",
    surname: "McCrory",
    birthdate: "17/08/1968",
    deathdate : "null",
    age: 51,
    ethnicity: "White",
    nationality: "British",
    gender: "Female",
},{
    image : "/paulanderson.jpg",
    description: "Actor",
    fame: true,
    name: "Paul",
    surname: "Anderson",
    birthdate: "12/02/1978",
    deathdate : "null",
    age: 42,
    ethnicity: "White",
    nationality: "British",
    gender: "Male",
},{
    image : "/anabellewallis.jpg",
    description: "Actress",
    fame: true,
    name: "Annabelle",
    surname: "Wallis",
    birthdate: "25/07/1984",
    deathdate : "null",
    age: 35,
    ethnicity: "White",
    nationality: "British",
    gender: "Female",
},{
    image : "/sophierundle.jpg",
    description: "Actress",
    fame: true,
    name: "Sophie",
    surname: "Rundle",
    birthdate: "21/04/1988",
    deathdate : "null",
    age: 31,
    ethnicity: "White",
    nationality: "British",
    gender: "Female",
},{
    image : "/tomhardy.jpg",
    description: "Actor/Producer",
    fame: true,
    name: "Tom",
    surname: "Hardy",
    birthdate: "15/09/1977",
    deathdate : "null",
    age: 42,
    ethnicity: "White",
    nationality: "British",
    gender: "Male",
},{
    image : "/aimeeffionedwards.jpg",
    description: "Actress",
    fame: true,
    name: "Aimee-Ffion",
    surname: "Edwards",
    birthdate: "21/11/1987",
    deathdate : "null",
    age: 32,
    ethnicity: "White",
    nationality: "British",
    gender: "Female",
},{
    image : "/natashao.jpg",
    description: "Actress",
    fame: true,
    name: "Natasha",
    surname: "O'Keeffe",
    birthdate: "21/11/1986",
    deathdate : "null",
    age: 31,
    ethnicity: "White",
    nationality: "British",
    gender: "Female",
},{
    image : "/4818-haluk-bilginer.jpg",
    description: "Actor",
    fame: true,
    name: "Haluk",
    surname: "Bilginer",
    birthdate: "05/06/1954",
    deathdate : "null",
    age: 65,
    ethnicity: "Turk",
    nationality: "Turkish",
    gender: "Male",
},{
    image : "/metin-akdulger.jpg",
    description: "Actor",
    fame: true,
    name: "Metin",
    surname: "Akdülger",
    birthdate: "05/06/1988",
    deathdate : "null",
    age: 32,
    ethnicity: "Turk",
    nationality: "Turkish",
    gender: "Male",
},{
    image : "/sebnembozoklu-750x375-c.jpg",
    description: "Actress/Producer",
    fame: true,
    name: "Sebnem",
    surname: "Bozoklu",
    birthdate: "20/18/1979",
    deathdate : "null",
    age: 40,
    ethnicity: "Turk",
    nationality: "Turkish",
    gender: "Female",
},{
    image : "/ali-atay_2200_b.jpg",
    description: "Actor/Writer/Producer",
    fame: true,
    name: "Ali",
    surname: "Atay",
    birthdate: "20/04/1976",
    deathdate : "null",
    age: 43,
    ethnicity: "Turk",
    nationality: "Turkish",
    gender: "Male",
},{
    image : "/cengizbozkurt.jpg",
    description: "Actor",
    fame: true,
    name: "Cengiz",
    surname: "Bozkurt",
    birthdate: "24/12/1965",
    deathdate : "null",
    age: 55,
    ethnicity: "Turk",
    nationality: "Turkish",
    gender: "Male",
},{
    image : "/serkankeskin.jpg",
    description: "Actor",
    fame: true,
    name: "Serkan",
    surname: "Keskin",
    birthdate: "25/11/1977",
    deathdate : "null",
    age: 42,
    ethnicity: "Turk",
    nationality: "Turkish",
    gender: "Male",
},{
    image : "/Melis-Birkan.jpg",
    description: "Actress",
    fame: true,
    name: "Melis",
    surname: "Birkan",
    birthdate: "30/10/1981",
    deathdate : "null",
    age: 38,
    ethnicity: "Turk",
    nationality: "Turkish",
    gender: "Female",
},{
    image : "/ahmetkural.jpg",
    description: "Actor",
    fame: true,
    name: "Ahmet",
    surname: "Kural",
    birthdate: "10/11/1982",
    deathdate : "null",
    age: 37,
    ethnicity: "Turk",
    nationality: "Turkish",
    gender: "Male",
},{
    image : "/murat-cemcir-depo_1_1_1577709908-400x400.jpg",
    description: "Actor",
    fame: true,
    name: "Murat",
    surname: "Cemcir",
    birthdate: "30/11/1976",
    deathdate : "null",
    age: 43,
    ethnicity: "Turk",
    nationality: "Turkish",
    gender: "Male",
},{
    image : "/Seda_Bakan_at_Tolgshow_1_(cropped).jpg",
    description: "Actress",
    fame: true,
    name: "Seda",
    surname: "Bakan",
    birthdate: "10/10/1985",
    deathdate : "null",
    age: 35,
    ethnicity: "Turk",
    nationality: "Turkish",
    gender: "Female",
},{
    image : "/Ali-Ihsan-Varol.jpg",
    description: "Actor",
    fame: true,
    name: "Ali Ihsan",
    surname: "Varol",
    birthdate: "28/06/1976",
    deathdate : "null",
    age: 43,
    ethnicity: "Turk",
    nationality: "Turkish",
    gender: "Male",
},{
    image : "/366x218-ipek-yaylacioglu-kimdir-1516195390706.jpg",
    description: "Actress",
    fame: true,
    name: "Ipek",
    surname: "Yaylacioglu",
    birthdate: "01/01/1984",
    deathdate : "null",
    age: 34,
    ethnicity: "Turk",
    nationality: "Turkish",
    gender: "Female",
},{
    image : "/fulden-akyurek.jpg",
    description: "Actress",
    fame: true,
    name: "Fulden",
    surname: "Akyürek",
    birthdate: "25/01/1980",
    deathdate : "null",
    age: 40,
    ethnicity: "Turk",
    nationality: "Turkish",
    gender: "Female",
},{
    image : "/bernauckaleler.jpg",
    description: "Actress",
    fame: true,
    name: "Berna",
    surname: "Üçkaleler",
    birthdate: "27/03/1987",
    deathdate : "null",
    age: 32,
    ethnicity: "Turk",
    nationality: "Turkish",
    gender: "Female",
},{
    image : "/erdal-besikcioglu-hepimiz-ayni-gemideyiz--1542016298.jpg",
    description: "Actor",
    fame: true,
    name: "Erdal",
    surname: "Besikçioglu",
    birthdate: "05/01/1970",
    deathdate : "null",
    age: 50,
    ethnicity: "Turk",
    nationality: "Turkish",
    gender: "Male",
},{
    image : "/berkan-sal-toraman-kimdir_16_9_1523969383.jpg",
    description: "Actor",
    fame: true,
    name: "Berkan",
    surname: "Sal",
    birthdate: "01/01/1969",
    deathdate : "null",
    age: 51,
    ethnicity: "Turk",
    nationality: "Turkish",
    gender: "Male",
},{
    image : "/nejat-isler-fotograf_16_9_1557820403_1_1_1576305656-400x400.jpg",
    description: "Actor",
    fame: true,
    name: "Nejat",
    surname: "Isler",
    birthdate: "29/02/1972",
    deathdate : "null",
    age: 48,
    ethnicity: "Turk",
    nationality: "Turkish",
    gender: "Male",
},{
    image : "/murat-yildirim-400.jpg",
    description: "Actor",
    fame: true,
    name: "Murat",
    surname: "Yildirim",
    birthdate: "13/04/1979",
    deathdate : "null",
    age: 41,
    ethnicity: "Turk",
    nationality: "Turkish",
    gender: "Male",
},{
    image : "/aslienver.jpg",
    description: "Actress",
    fame: true,
    name: "Asli",
    surname: "Enver",
    birthdate: "10/03/1984",
    deathdate : "null",
    age: 36,
    ethnicity: "Turk",
    nationality: "Turkish",
    gender: "Female",
},{
    image : "/mehmetozgur.jpg",
    description: "Actor/Producer",
    fame: true,
    name: "Mehmet",
    surname: "Özgür",
    birthdate: "30/08/1970",
    deathdate : "null",
    age: 49,
    ethnicity: "Turk",
    nationality: "Turkish",
    gender: "Male",
},{
    image : "/pelinakil.jpg",
    description: "Actress",
    fame: true,
    name: "Pelin",
    surname: "Akil",
    birthdate: "17/04/1986",
    deathdate : "null",
    age: 34,
    ethnicity: "Turk",
    nationality: "Turkish",
    gender: "Female",
},{
    image : "/ata-demirer_9896_b.jpg",
    description: "Actor/Scriptwriter",
    fame: true,
    name: "Ata",
    surname: "Demirer",
    birthdate: "06/07/1972",
    deathdate : "null",
    age: 47,
    ethnicity: "Turk", 
    nationality: "Turkish",
    gender: "Male",
},{
    image : "/gülse-birsel.jpg",
    description: "Actress",
    fame: true,
    name: "Gülse",
    surname: "Birsel",
    birthdate: "11/03/1971",
    deathdate : "null",
    age: 49,
    ethnicity: "Turk",
    nationality: "Turkish",
    gender: "Female",
},{
    image : "/timuracar.jpg",
    description: "Actor/Producer",
    fame: true,
    name: "Timur",
    surname: "Acar",
    birthdate: "11/03/1979",
    deathdate : "null",
    age: 40,
    ethnicity: "Turk",
    nationality: "Turkish",
    gender: "Male",
},{
    image : "/cemyilmaz.jpg",
    description: "Actor/Scriptwriter/Producer",
    fame: true,
    name: "Cem",
    surname: "Yilmaz",
    birthdate: "23/04/1973",
    deathdate : "null",
    age: 46,
    ethnicity: "Turk",
    nationality: "Turkish",
    gender: "Male",
},{
    image : "/ozangüven.jpg",
    description: "Actor/Scriptwriter",
    fame: true,
    name: "Ozan",
    surname: "Güven",
    birthdate: "19/04/1975",
    deathdate : "null",
    age: 44,
    ethnicity: "Turk",
    nationality: "Turkish",
    gender: "Male",
},{
    image : "/arianagrande.jpg",
    description: "Singer",
    fame: true,
    name: "Ariana",
    surname: "Grande",
    birthdate: "26/06/1993",
    deathdate : "null",
    age: 27,
    ethnicity: "N/N",
    nationality: "American",
    gender: "Female",
},{
    image : "/billieellish.jpg",
    description: "Singer",
    fame: true,
    name: "Billie",
    surname: "Eilish",
    birthdate: "18/12/2001",
    deathdate : "null",
    age: 19,
    ethnicity: "N/N",
    nationality: "American",
    gender: "Female",
},{
    image : "/edsheeran.jpg",
    description: "Singer",
    fame: true,
    name: "Ed",
    surname: "Sheeran",
    birthdate: "17/02/1991",
    deathdate : "null",
    age: 29,
    ethnicity: "N/N",
    nationality: "British",
    gender: "Male",
},{
    image : "/shawn-mendes.jpg",
    description: "Singer",
    fame: true,
    name: "Shawn",
    surname: "Mendes",
    birthdate: "08/08/1998",
    deathdate : "null",
    age: 22,
    ethnicity: "N/N",
    nationality: "Canadian",
    gender: "Male",
},{
    image : "/taylorswift.jpg",
    description: "Singer",
    fame: true,
    name: "Taylow",
    surname: "Swift",
    birthdate: "13/12/1989",
    deathdate : "null",
    age: 22,
    ethnicity: "N/N",
    nationality: "American",
    gender: "Female",
},{
    image : "/selenagomez.jpg",
    description: "Singer",
    fame: true,
    name: "Selena",
    surname: "Gomez",
    birthdate: "22/01/1992",
    deathdate : "null",
    age: 28,
    ethnicity: "N/N",
    nationality: "American",
    gender: "Female",
},{
    image : "/brunomars.jpg",
    description: "Singer",
    fame: true,
    name: "Bruno",
    surname: "Mars",
    birthdate: "09/01/1985",
    deathdate : "null",
    age: 35,
    ethnicity: "N/N",
    nationality: "American",
    gender: "Male",
},{
    image : "/beyonce.jpg",
    description: "Singer",
    fame: true,
    name: "Beyoncé",
    surname: "Knowles",
    birthdate: "04/09/1981",
    deathdate : "null",
    age: 39,
    ethnicity: "N/N",
    nationality: "American",
    gender: "Female",
},{
    image : "/ladygaga.jpg",
    description: "Singer",
    fame: true,
    name: "Lady",
    surname: "Gaga",
    birthdate: "04/09/1986",
    deathdate : "null",
    age: 34,
    ethnicity: "N/N",
    nationality: "American",
    gender: "Female",
},{
    image : "/dualipa.jpg",
    description: "Singer",
    fame: true,
    name: "Dua",
    surname: "Lipa",
    birthdate: "22/08/1995",
    deathdate : "null",
    age: 25,
    ethnicity: "N/N",
    nationality: "British",
    gender: "Female",
},{  image : "/Katy_Perry_2019_(cropped).jpg",
    description: "Singer",
    fame: true,
    name: "Katty",
    surname: "Perry",
    birthdate: "25/01/1984",
    deathdate : "null",
    age: 36,
    ethnicity: "N/N",
    nationality: "American",
    gender: "Female",
},{
    image : "/demilovato.jpg",
    description: "Singer",
    fame: true,
    name: "Demi",
    surname: "Lovato",
    birthdate: "20/08/1992",
    deathdate : "null",
    age: 29,
    ethnicity: "N/N",
    nationality: "American",
    gender: "Female",
},{
    image : "/nickjonas.jpg",
    description: "Singer",
    fame: true,
    name: "Nick",
    surname: "Jonas",
    birthdate: "16/09/1992",
    deathdate : "null",
    age: 29,
    ethnicity: "N/N",
    nationality: "American",
    gender: "Male",
},{
    image : "/annemarie.jpg",
    description: "Singer",
    fame: true,
    name: "Anne",
    surname: "Marie",
    birthdate: "07/04/1991",
    deathdate : "null",
    age: 29,
    ethnicity: "N/N",
    nationality: "British",
    gender: "Female",
},{
    image : "/justinbieber.jpg",
    description: "Singer",
    fame: true,
    name: "Justin",
    surname: "Bieber",
    birthdate: "01/03/1994",
    deathdate : "null",
    age: 29,
    ethnicity: "N/N",
    nationality: "Canadian",
    gender: "Male",
},{
    image : "/jenniferlopez.jpg",
    description: "Singer",
    fame: true,
    name: "Jennifer",
    surname: "Lopez",
    birthdate: "24/07/1969",
    deathdate : "null",
    age: 51,
    ethnicity: "N/N",
    nationality: "American",
    gender: "Female",
},{
    image : "/mileycyrus.jpg",
    description: "Singer",
    fame: true,
    name: "Miley",
    surname: "Cyrus",
    birthdate: "23/11/1992",
    deathdate : "null",
    age: 28,
    ethnicity: "N/N",
    nationality: "American",
    gender: "Female",
},{
    image : "/avrillavigne.jpg",
    description: "Singer",
    fame: true,
    name: "Avril",
    surname: "Lavigne",
    birthdate: "27/09/1984",
    deathdate : "null",
    age: 36,
    ethnicity: "N/N",
    nationality: "Canadian",
    gender: "Female",
},{
    image : "/normani.jpg",
    description: "Singer",
    fame: true,
    name: "Normani",
    surname: "",
    birthdate: "31/05/1996",
    deathdate : "null",
    age: 24,
    ethnicity: "Black",
    nationality: "American",
    gender: "Female",
},{
    image : "/madonna.jpg",
    description: "Singer",
    fame: true,
    name: "Madonna",
    surname: "",
    birthdate: "16/08/1958",
    deathdate : "null",
    age: 62,
    ethnicity: "N/N",
    nationality: "American",
    gender: "Female",
},{
    image : "/chrisbrown.jpg",
    description: "Singer",
    fame: true,
    name: "Chris",
    surname: "Brown",
    birthdate: "05/05/1989",
    deathdate : "null",
    age: 31,
    ethnicity: "N/N",
    nationality: "American",
    gender: "Female",
},{
    image : "/sezenaksu.jpg",
    description: "Singer",
    fame: true,
    name: "Sezen",
    surname: "Aksu",
    birthdate: "13/06/1954",
    deathdate : "null",
    age: 65,
    ethnicity: "Turk",
    nationality: "Turkish",
    gender: "Female",
},{
    image : "/askin-nur-yengi-20181011163530.jpg",
    description: "Singer",
    fame: true,
    name: "Askin Nur",
    surname: "Yengi",
    birthdate: "03/07/1970",
    deathdate : "null",
    age: 49,
    ethnicity: "Turk",
    nationality: "Turkish",
    gender: "Female",
},{
    image : "/asligungor.jpg",
    description: "Singer",
    fame: true,
    name: "Asli",
    surname: "Güngor",
    birthdate:"27/09/1979",
    deathdate : "null",
    age: 40,
    ethnicity: "Turk",
    nationality: "Turkish",
    gender: "Female",
},{
    image : "/demetakalin-depophotos_16_9_1582889749.jpg",
    description: "Singer",
    fame: true,
    name: "Demet",
    surname: "Akalin",
    birthdate: "23/04/1972",
    deathdate : "null",
    age: 47,
    ethnicity: "Turk",
    nationality: "Turkish",
    gender: "Female",
},{
    image : "/candanercetin.jpg",
    description: "Singer",
    fame: true,
    name: "Candan",
    surname: "Erçetin",
    birthdate: "10/02/1963",
    deathdate : "null",
    age: 57,
    ethnicity: "Turk",
    nationality: "Turkish",
    gender: "Female",
},{
    image : "/tarkan.jpg",
    description: "Singer",
    fame: true,
    name: "Tarkan",
    surname: "Tevetoglu",
    birthdate: "17/10/1972",
    deathdate : "null",
    age: 47,
    ethnicity: "Turk",
    nationality: "Turkish",
    gender: "Male",
},{
    image : "/ebrugundes.jpg",
    description: "Singer",
    fame: true,
    name: "Ebru",
    surname: "Gündes",
    birthdate: "12/10/1974",
    deathdate : "null",
    age: 45,
    ethnicity: "Turk",
    nationality: "Turkish",
    gender: "Female",
},{
    image : "/gülsen.jpg",
    description: "Singer",
    fame: true,
    name: "Gülsen",
    surname: "Bayraktar",
    birthdate: "29/05/1976",
    deathdate : "null",
    age: 43,
    ethnicity: "Turk",
    nationality: "Turkish",
    gender: "Female",
},{
    image : "/atiye.jpg",
    description: "Singer",
    fame: true,
    name: "D. Atiye",
    surname: "Yilmaz",
    birthdate: "22/11/1988",
    deathdate : "null",
    age: 31,
    ethnicity: "Turk",
    nationality: "Turkish",
    gender: "Female",
},{
    image : "/aleynatilki.jpg",
    description: "Singer",
    fame: true,
    name: "Aleyna",
    surname: "Tilki",
    birthdate: "28/03/2000",
    deathdate : "null",
    age: 20,
    ethnicity: "Turk",
    nationality: "Turkish",
    gender: "Female",
},{
    image : "/baris-manco-depo-2_1_1_1580537738-400x400.jpg",
    description: "Singer/Writer",
    fame: true,
    name: "Baris",
    surname: "Manço",
    birthdate: "02/01/1943",
    deathdate : "01/02/1999",
    age: 56,
    ethnicity: "Turk",
    nationality: "Turkish",
    gender: "Male",
},{
    image : "/hadise.jpg",
    description: "Singer",
    fame: true,
    name: "Hadise",
    surname: "Açikgöz",
    birthdate: "22/10/1985",
    deathdate : "null",
    age: 34,
    ethnicity: "Turk",
    nationality: "Turkish",
    gender: "Female",
},{
    image : "/hande-yener-sli_16_9_1553490859.jpg",
    description: "Singer",
    fame: true,
    name: "Hande",
    surname: "Yener",
    birthdate: "13/01/1973",
    deathdate : "null",
    age: 47,
    ethnicity: "Turk",
    nationality: "Turkish",
    gender: "Female",
},{
    image : "/ferhatgocer.jpg",
    description: "Singer",
    fame: true,
    name: "Ferhat",
    surname: "Göçer",
    birthdate: "11/05/1970",
    deathdate : "null",
    age: 49,
    ethnicity: "Turk",
    nationality: "Turkish",
    gender: "Male",
},{
    image : "/gokhan-ozen-sli_1_1_1552971928-400x400.jpg",
    description: "Singer",
    fame: true,
    name: "Gökhan",
    surname: "Özen",
    birthdate: "29/10/1979",
    deathdate : "null",
    age: 40,
    ethnicity: "Turk",
    nationality: "Turkish",
    gender: "Male",
},{
    image : "/cemkaraca.jpg",
    description: "Singer",
    fame: true,
    name: "Cem",
    surname: "Karaca",
    birthdate: "05/04/1945",
    deathdate : "08/02/2004",
    age: 59,
    ethnicity: "Turk",
    nationality: "Turkish",
    gender: "Male",
},{
    image : "/ahmetkaya.jpg",
    description: "Singer",
    fame: true,
    name: "Ahmet",
    surname: "Kaya",
    birthdate: "28/10/1957",
    deathdate : "16/10/2000",
    age: 43,
    ethnicity: "Turk",
    nationality: "Turkish",
    gender: "Male",
},{
    image : "/sebnemferah.jpg",
    description: "Singer",
    fame: true,
    name: "Sebnem",
    surname: "Ferah",
    birthdate: "12/04/1972",
    deathdate : "null",
    age: 48,
    ethnicity: "Turk",
    nationality: "Turkish",
    gender: "Female",
},{
    image : "/czn.jpg",
    description: "Chief / Instagrammer",
    fame: true,
    name: "Burak",
    surname: "Özdemir (CZN)",
    birthdate: "24/03/1994",
    deathdate : "null",
    age: 26,
    ethnicity: "Turk",
    nationality: "Turkish",
    gender: "Male",
},{
    image : "/nusret.jpg",
    description: "Butcher",
    fame: true,
    name: "Nusret",
    surname: "Gökçe",
    birthdate: "09/08/1983",
    deathdate : "null",
    age: 36,
    ethnicity: "Turk",
    nationality: "Turkish",
    gender: "Male",
},{
    image : "/orkunisitmak.jpg",
    description: "Youtuber",
    fame: true,
    name: "Orkun",
    surname: "Isitmak",
    birthdate: "08/01/1996",
    deathdate : "null",
    age: 24,
    ethnicity: "Turk",
    nationality: "Turkish",
    gender: "Male",
},{
    image : "/muratgf.jpg",
    description: "Youtuber",
    fame: true,
    name: "Murat Engin",
    surname: "Ekin",
    birthdate: "09/10/1997",
    deathdate : "null",
    age: 23,
    ethnicity: "Turk",
    nationality: "Turkish",
    gender: "Male",
},{
    image : "/enes-batur_1_1_1577371733-400x400.jpg",
    description: "Youtuber",
    fame: true,
    name: "Enes",
    surname: "Batur",
    birthdate: "09/04/1998",
    deathdate : "null",
    age: 22,
    ethnicity: "Turk",
    nationality: "Turkish",
    gender: "Male",
},{
    image : "/reynmen.jpg",
    description: "Vlogger/Singer",
    fame: true,
    name: "Yusuf",
    surname: "Aktas",
    birthdate: "06/11/1995",
    deathdate : "null",
    age: 24,
    ethnicity: "Turk",
    nationality: "Turkish",
    gender: "Male",
},{
    image : "/tabutcu1.jpg",
    description: "Most Famous XD",
    fame: true,
    name: "Coffin Man",
    surname: "1",
    birthdate: "01/1/2020",
    deathdate : "null",
    age: 1,
    ethnicity: "Black",
    nationality: "African",
    gender: "Male",
},{
    image : "/tabutcu2.jpg",
    description: "Most Famous XD",
    fame: true,
    name: "Coffin Man",
    surname: "2",
    birthdate: "01/1/2020",
    deathdate : "null",
    age: 1,
    ethnicity: "Black",
    nationality: "African",
    gender: "Male",
},{
    image : "/tabutcu3.jpg",
    description: "Most Famous XD",
    fame: true,
    name: "Coffin Man",
    surname: "3",
    birthdate: "01/1/2020",
    deathdate : "null",
    age: 1,
    ethnicity: "Black",
    nationality: "African",
    gender: "Male",
},{
    image : "/tabutcu4.jpg",
    description: "Most Famous XD",
    fame: true,
    name: "Coffin Man",
    surname: "4",
    birthdate: "01/1/2020",
    deathdate : "null",
    age: 1,
    ethnicity: "Black",
    nationality: "African",
    gender: "Male",
},{
    image : "/barisözcan.jpg",
    description: "Youtuber",
    fame: true,
    name: "Baris",
    surname: "Özcan",
    birthdate: "23/07/1974",
    deathdate : "null",
    age: 45,
    ethnicity: "Turk",
    nationality: "Turkish",
    gender: "Male",
},{
    image : "/oguzhanugur.jpg",
    description: "Singer/Youtuber",
    fame: true,
    name: "Oguzhan",
    surname: "Ugur",
    birthdate: "29/01/1984",
    deathdate : "null",
    age: 36,
    ethnicity: "Turk",
    nationality: "Turkish",
    gender: "Male",
},{
    image : "/halilsoyletmez.jpg",
    description: "Youtuber",
    fame: true,
    name: "Halil",
    surname: "Söyletmez",
    birthdate: "19/03/1992",
    deathdate : "null",
    age: 28,
    ethnicity: "Turk",
    nationality: "Turkish",
    gender: "Male",
},{
    image : "/kerimcan.jpg",
    description: "DJ",
    fame: true,
    name: "Kerimcan",
    surname: "Durmaz",
    birthdate: "02/11/1994",
    deathdate : "null",
    age: 25,
    ethnicity: "Turk",
    nationality: "Turkish",
    gender: "Male",
},{
    image : "/elonmusk.jpg",
    description: "CEO / Tesla",
    fame: true,
    name: "Elon",
    surname: "Musk",
    birthdate: "28/06/1971",
    deathdate : "null",
    age: 38,
    ethnicity: "White African",
    nationality: "South Africa",
    gender: "Male",
},{
    image : "/ezhel.jpg",
    description: "Rapper",
    fame: true,
    name: "Ezhel",
    surname: "",
    birthdate: "01/07/1990",
    deathdate : "null",
    age: 29,
    ethnicity: "Turk",
    nationality: "Turkish",
    gender: "Male",
},{
    image : "/berkcanguven.jpg",
    description: "Youtuber",
    fame: true,
    name: "Berkcan",
    surname: "Güven",
    birthdate: "30/05/1996",
    deathdate : "null",
    age: 23,
    ethnicity: "Turk",
    nationality: "Turkish",
    gender: "Male",
},{
    image : "/duygukoseoglu.jpg",
    description: "Youtuber",
    fame: true,
    name: "Duygu",
    surname: "Köseoglu",
    birthdate: "08/02/1994",
    deathdate : "null",
    age: 26,
    ethnicity: "Turk",
    nationality: "Turkish",
    gender: "Female",
},{
    image : "/normender.jpg",
    description: "Rapper",
    fame: true,
    name: "Norm",
    surname: "Ender",
    birthdate: "25/05/1985",
    deathdate : "null",
    age: 35,
    ethnicity: "Turk",
    nationality: "Turkish",
    gender: "Male",
},{
    image : "/urasbenlioglu.jpg",
    description: "Youtuber",
    fame: true,
    name: "Uras",
    surname: "Benlioglu",
    birthdate: "16/02/1982",
    deathdate : "null",
    age: 38,
    ethnicity: "Turk",
    nationality: "Turkish",
    gender: "Male",
},{
    image : "/acun.jpg",
    description: "Producer",
    fame: true,
    name: "Acun",
    surname: "Ilicali",
    birthdate: "29/05/1969",
    deathdate : "null",
    age: 50,
    ethnicity: "Turk",
    nationality: "Turkish",
    gender: "Male",
},{
    image : "/ruhicenet.jpg",
    description: "Youtuber",
    fame: true,
    name: "Ruhi",
    surname: "Çenet",
    birthdate: "20/10/1990",
    deathdate : "null",
    age: 29,
    ethnicity: "Turk",
    nationality: "Turkish",
    gender: "Male",
},{
    image : "/cuneyt-ozdemir.jpg",
    description: "Journalist",
    fame: true,
    name: "Cüneyt",
    surname: "Özdemir",
    birthdate: "08/02/1970",
    deathdate : "null",
    age: 50,
    ethnicity: "Turk",
    nationality: "Turkish",
    gender: "Male",
},{
    image : "/basakkarahan.jpg",
    description: "Youtuber",
    fame: true,
    name: "Basak",
    surname: "Karahan",
    birthdate: "03/08/1998",
    deathdate : "null",
    age: 21,
    ethnicity: "Turk",
    nationality: "Turkish",
    gender: "Female",
},{
    image : "/barisakarsu.jpg",
    description: "Singer",
    fame: true,
    name: "Baris",
    surname: "Akarsu",
    birthdate: "29/06/1979",
    deathdate : "04/07/2007",
    age: 28,
    ethnicity: "Turk",
    nationality: "Turkish",
    gender: "Male",
},{
    image : "/selcukbuyuk.jpg",
    description: "Instagrammer",
    fame: true,
    name: "Selçuk",
    surname: "Büyük",
    birthdate: "15/04/1996",
    deathdate : "null",
    age: 25,
    ethnicity: "Turk",
    nationality: "Turkish",
    gender: "Male",
}]






















